title: Future Linux
description: An Future Linux Distribution for Creatives Everywhere :)
url: "https://futurelinux.github.io"
username: Future Linux
user_description: Future Linux is a rolling-release distribution aimed at Creative Multi-Media and Gaming Enthusiasts.
user_title: An Future Linux Operating System
email: future_linux@163.com
github_username:  futurelinux
show_downloads: true
google_analytics:
exclude: ['package.json', 'src' , 'node_modules', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
theme: jekyll-theme-hacker
